### ISSUE TITLE
Error: Cannot find module 'underscore.string'

### ISSUE THREAD

**Issue by val-samonte** [geowarin/generator-phaser-gulp-typescript#3]
Running 'yo phaser-gulp-typescript' on windows command prompt gave me the ff:

Error: Cannot find module 'underscore.string'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\valsa_000\AppData\Roaming\npm\node_modules\g
enerator-phaser-gulp-typescript\app\index.js:7:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by digital-synapse** [comment]
I get the same thing. :( is there a fix for this?

**Comment by digital-synapse** [comment]
0.2.1 seems to be the last version that does not throw the underscore.string error

**Comment by ergwun** [comment]
Install underscore.string globally to work around this issue.

`npm install -g underscore.string`
